### ISSUE TITLE
Neovim Support for Elm Syntax

### ISSUE THREAD

**Issue by andys8** [andys8/vim-elm-syntax#9]
It looks like elm support is still missing in neovim.

Vim:
https://github.com/vim/vim/blob/master/runtime/syntax/elm.vim

Neovim (missing as of today):
https://github.com/neovim/neovim/tree/master/runtime/syntax

I assumed, these runtime patches will find it's way into neovim, too. But maybe somebody has to create an explicit PR? Does somebody want to dig into that?

## NeoVim Patch PRs

This is how Vim patches that are merged into neovim look like:

https://github.com/neovim/neovim/pulls?q=vim-patch+

### PR

https://github.com/vim/vim/pull/6157

### Runtime update

https://github.com/vim/vim/commit/acc224064033e5cea21ef7f1eefb356ca06ff11d#diff-6189986fbc5a8d68cbeb136221f76964ef0b68a961a5d3c4202482aada9b83fe

**Comment by pehota** [comment]
@andys8 , I can try to handle that.

**Comment by pehota** [comment]
So, it turns out there is a patch for the file type detection that has already been applied to neovim (https://github.com/neovim/neovim/pull/12403) but the syntax, ftplugin and indent files are missing from said patch. I couldn't find a Vim patch for the those files, so I opened an [issue](https://github.com/neovim/neovim/issues/13193) in neovim because I am not sure how to proceed (the `contribution` readme doesn't help in this case, although I think just porting the files and opening a PR should be fine). Waiting for the neovim guys to reply.

**Comment by andys8** [comment]
Nice. Thanks a lot

**Comment by andys8** [comment]
Will be solved with https://github.com/neovim/neovim/issues/13193

**Comment by pehota** [comment]
Hey, long time.
I opened a PR for the changes: https://github.com/neovim/neovim/pull/13678.
I am waiting for a review but I expect there might be more work involved as I am not sure I created the patch correctly. Lets see.

**Comment by andys8** [comment]
https://github.com/neovim/neovim/pull/13718 was merged. Thanks a lot
